name: Coverage

on:
  push:
    branches: master
  pull_request:
  schedule:
    - cron: '00 07 * * 0'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
        
      - name: Cache .cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: coverage-cargo-folder
            
      - name: Install tarpaulin
        run: |
          sudo apt-get install libssl-dev
          cargo install cargo-tarpaulin
          
      - name: Generate and Upload Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cargo tarpaulin -v --out Xml
          bash <(curl -s https://codecov.io/bash)
